scrape_configs:
  - job_name: node
    scrape_interval: 5s
    static_configs:
    - targets: ['node-exporter:9100']
 
  - job_name: pushgateway
    honor_labels: false
    static_configs:
    - targets: ['localhost:9091']
      labels:
        pushgateway_instance: metricfire
